version: "2.3"

# How to override the configuration when doing development, so that yarn
# packages from the local system are used.
services:
  node: {}
#    volumes:
#      # MacOS
#      - source: ~/Library/Caches/Yarn/v6
#        target: /usr/local/share/.cache/yarn/v6
#        type: bind
#      # Linux:
#      - source: ~/.cache/yarn/v6
#        target: /usr/local/share/.cache/yarn/v6
#        type: bind
