name: Monofo
description: Dynamically generates monorepo pipelines from multiple subprojects
author: https://github.com/vital-software
requirements:
  - git
  - aws
  - npx
  - mktemp
configuration:
  properties:
    generate:
      type: string
      enum:
        - pipeline
    upload:
      type: object
      patternProperties:
        '^[^/]*\.tar(\.lz4|\.caidx)?$':
          oneOf:
            - type: array
              items:
                type: string
            - type: object
              required:
                - files-from
              properties:
                "files-from": { type: string }
                null: { type: string }
              additionalProperties: false
      additionalProperties: false
    download: {}
  additionalProperties: false
