name: Monofo
description: Dynamically generates monorepo pipelines from multiple subprojects
author: https://github.com/vital-software
requirements:
  - git
  - npx
  - mktemp
  - bash
  - cat
  - mkdir
configuration:
  properties:
    generate:
      type: string
      enum:
        - pipeline
    upload:
      type: object
      patternProperties:
        '^[^/]+$':
          oneOf:
            - type: array
              items:
                type: string
            - type: object
              required:
                - filesFrom
              properties:
                filesFrom: { type: string }
                null:      { type: boolean }
              additionalProperties: false
    download:
      oneOf:
        - type: string
        - type: array
          items:
            type: string
  additionalProperties: false
