---

monorepo:
  pure: true
  expects: node-modules.caidx
  matches:
    - "**/*.ts"
    - tsconfig.json
    - package.json
    - yarn.lock
  produces: typescript.caidx

steps:
  - name: ":typescript: Build"
    key: typescript
    depends_on:
      - node-image
      - node-modules
    commands:
      - yarn build
    timeout_in_minutes: 20
    plugins:
      - docker-compose#v3.9.0:
          run: node
      - vital-software/monofo#v3.7.1:
          download:
            - node-modules.caidx
          upload:
            typescript.caidx:
              - ./dist/
