---

monorepo:
  pure: true
  matches:
    - package.json
    - yarn.lock
  produces: node-modules.catar.caibx

steps:
  - name: ":yarn: Install"
    key: node-modules
    depends_on:
      - node-image
    command: yarn install --frozen-lockfile
    timeout_in_minutes: 20
    env:
      MONOFO_ARTIFACT_NODE_MODULES_BUILD_ID: $MONOFO_BASE_BUILD_ID
      MONOFO_ARTIFACT_NODE_MODULES_SOFT_FAIL: 1 # because only used for pre-cache
    plugins:
      - docker-compose#v3.9.0:
          run: node
      - vital-software/monofo#v4.0.3:
          download: node-modules.catar.caibx # pre-cache the old node_modules into place before yarn install
          upload:
            node-modules.catar.caibx:
              - ./node_modules/

