monorepo:
  pure: true
  matches:
    - plugin.yml
    - "**/*.md"
    - .buildkite/plugin-lint

steps:
  - name: ":buildkite: Plugin Lint"
    key: plugin-lint
    timeout_in_minutes: 20
    plugins:
      - docker-compose#v3.9.0:
          run: plugin-lint
    soft_fail: # until we can fix https://github.com/buildkite-plugins/buildkite-plugin-linter/issues/409
      - exit_status: 1
