env:
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_CONFIG_0: "docker-compose.yml"
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_CONFIG_1: "docker-compose.buildkite.yml"

monorepo:
  pure: true
  expects: node-modules.tar.lz4
  matches:
    - "**/*.ts"
    - tsconfig.json
    - package.json
    - yarn.lock
  produces: typescript.tar.lz4

steps:
  - name: ":typescript: Build"
    key: typescript
    depends_on:
      - node-image
      - node-modules
    commands:
      - yarn build
    timeout_in_minutes: 20
    plugins:
      - docker-compose#v3.9.0:
          run: node
      - vital-software/monofo#v3.4.2:
          download:
            - node-modules.tar.lz4
          upload:
            typescript.tar.lz4:
              - ./dist/
