env:
  NODE_ENV: development
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_CONFIG_0: "docker-compose.yml"
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_CONFIG_1: "docker-compose.buildkite.yml"

monorepo:
  matches: true # because whether we should run determined only by branch
  pure: false

steps:
  - label: ":shipit: Release"
    depends_on:
      - node-image
      - node-modules
      - typescript
      - test
      - lint
    command: yarn run release
    branches: main next next-major beta alpha
    plugins:
      - improbable-eng/metahook#v0.4.1:
          pre-command: >
            buildkite-agent artifact download node-modules.tar.lz4 . && tar -x --use-compress-program=lz4 -f node-modules.tar.lz4 && rm -rf node-modules.tar.lz4 &
            buildkite-agent artifact download typescript.tar.lz4 . && tar -x --use-compress-program=lz4 -f typescript.tar.lz4 && rm -rf typescript.tar.lz4 &
            wait
      - docker-compose#v3.9.0:
          run: node
      - seek-oss/aws-sm#v2.3.1:
          env:
            NPM_TOKEN: "global/npm-token"
