---

monorepo:
  matches: true # because whether we should run determined only by branch
  pure: false

steps:
  - label: ":shipit: Release"
    depends_on:
      - node-image
      - node-modules
      - typescript
      - test
      - lint
      - plugin-test
      - plugin-lint
    command: yarn run release
    branches: main next next-major beta alpha
    plugins:
      - improbable-eng/metahook#v0.4.1:
          pre-command: git fetch --tags -f # To allow mutating build tags for now
      - vital-software/monofo#v5.0.4:
          download:
            - node-modules.catar.caibx
            - typescript.catar.caibx
      - docker-compose#v3.9.0:
          run: node
      - seek-oss/aws-sm#v2.3.1:
          env:
            NPM_TOKEN: "global/npm-token"
