env:
  NODE_ENV: development
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_CONFIG_0: "docker-compose.yml"
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_CONFIG_1: "docker-compose.buildkite.yml"

monorepo:
  pure: true
  expects:
    - node-modules.tar.lz4
    - typescript.tar.lz4
  matches:
    - "**/*.ts"
    - "test/**/*.yml"
    - tsconfig.json
    - package.json
    - yarn.lock
    - .eslintrc.js

templates:
  # Plugin templates
  - &pre-command
    improbable-eng/metahook#v0.4.1:
      pre-command: >
        buildkite-agent artifact download node-modules.tar.lz4 . && tar -x --use-compress-program=lz4 -f node-modules.tar.lz4 && rm -rf node-modules.tar.lz4 &
        buildkite-agent artifact download typescript.tar.lz4 . && tar -x --use-compress-program=lz4 -f typescript.tar.lz4 && rm -rf typescript.tar.lz4 &
        wait
  - &dc
    docker-compose#v3.9.0:
      run: node

  # Step templates
  - &step
    timeout_in_minutes: 10
    depends_on:
      - node-image
      - node-modules
      - typescript
    retry:
      manual:
        permit_on_passed: true
    plugins:
      - *pre-command
      - *dc

steps:
  - label: ":jest: Test"
    key: test
    command: yarn test
    <<: *step

  - label: ":eslint: Lint"
    key: lint
    command: yarn lint
    <<: *step
