env:
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_CONFIG_0: "docker-compose.yml"
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_CONFIG_1: "docker-compose.buildkite.yml"
  MONOFO_HOOK_DEBUG: "1"

monorepo:
  pure: true
  matches:
    - package.json
    - yarn.lock
  produces: node-modules.caidx

steps:
  - name: ":yarn: Install"
    key: node-modules
    depends_on:
      - node-image
    command: yarn install --frozen-lockfile
    timeout_in_minutes: 20
    plugins:
      - docker-compose#v3.9.0:
          run: node
      - vital-software/monofo#v3.5.1:
          upload:
            node-modules.caidx:
              - ./node_modules/

