env:
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_CONFIG_0: "docker-compose.yml"
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_CONFIG_1: "docker-compose.buildkite.yml"

monorepo:
  pure: true
  expects: node-modules.tar.lz4
  matches:
    - "**/*.ts"
    - tsconfig.json
    - package.json
    - yarn.lock
  produces: typescript.tar.lz4

steps:
  - name: ":typescript: Build"
    key: typescript
    depends_on:
      - node-image
      - node-modules
    commands:
      - yarn build
      - tar -c --use-compress-program="lz4 -2" -f typescript.tar.lz4 dist/
    timeout_in_minutes: 20
    plugins:
      - improbable-eng/metahook#v0.4.1:
          pre-command: buildkite-agent artifact download node-modules.tar.lz4 . && tar -x --use-compress-program=lz4 -f node-modules.tar.lz4
      - docker-compose#v3.9.0:
          run: node
      - artifacts#v1.5.0:
          upload:
            - typescript.tar.lz4
