---

monorepo:
  pure: true
  expects:
    - node-modules.catar.caibx
    - typescript.catar.caibx
  matches:
    - "**/*.ts"
    - "test/**/*.yml"
    - tsconfig.json
    - package.json
    - yarn.lock
    - .eslintrc.js

templates:
  # Plugin templates
  - &dc
    docker-compose#v3.9.0:
      run: node

  # Step templates
  - &step
    timeout_in_minutes: 10
    depends_on:
      - node-image
      - node-modules
      - typescript
    retry:
      manual:
        permit_on_passed: true

steps:
  - label: ":jest: Test"
    key: test
    command: yarn test
    <<: *step
    plugins:
      - vital-software/monofo#v5.0.6:
          download:
            - node-modules.catar.caibx
            - typescript.catar.caibx
      - *dc

  - label: ":eslint: Lint"
    key: lint
    command: yarn lint
    <<: *step
    plugins:
      - vital-software/monofo#v5.0.6:
          download:
            - node-modules.catar.caibx
            - typescript.catar.caibx
      - *dc
